# Generated by Django 4.1.6 on 2023-02-10 08:57

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=250, verbose_name='Title')),
                ('Description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('State', models.BooleanField(default=False)),
                ('ImageEvent', models.ImageField(blank=True, upload_to='images/')),
                ('NombreParticipants', models.IntegerField(default=0)),
                ('Category', models.CharField(choices=[('Music', 'Music'), ('Sport', 'Sport'), ('Cinema', 'Cinema')], max_length=10, verbose_name='Category')),
                ('DateEvent', models.DateField(validators=[events.models.less_date])),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('UpdatedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePart', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
