# Generated by Django 4.1.6 on 2023-02-10 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': 'Participations'},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('person', 'event')},
        ),
    ]
